import MainNavigation from './home/MainNavigation';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <MainNavigation />
        <main className='max-w-4xl mx-auto px-10'>{children}</main>
      </body>
    </html>
  );
}
